
# Program

The course takes place on each working day from 9am – 1pm
(CEST). Short breaks will be scheduled between sessions.

The hands-on sessions consists of a set of questions and example
data. Solve the exercises by taking advantage of the online examples
and resources that are pointed out in the study material. There is
often more than one way to solve a given task. It is assumed that you
have already installed the required software. Do not hesitate to ask
support from the course assistants.

## Monday 12 July: from raw sequences to ecological data analysis

**Lectures**

 * Microbiota analysis: association studies vs. causality; microbiota sequencing methods (16S, shotgun, metagenomics) - by dr. Tom Ederveen (Radboud UMC Nijmegen, The Netherlands)

 * DNA isolation and 16S rRNA gene sequencing; bioinformatics step 1: from raw sequences to OTU table in a biom file – by Tom Ederveen (Radboudumc Nijmegen, The Netherlands)


**Demo & Practical**

 * Importing data to R for interactive data analysis 

 * Task: initialize reproducible report

----------------------------------------------------------------

## Tuesday 13 July - Alpha diversity 

**Demo**

- Microbiome data exploration

**Lecture**

- Key concepts in microbiome data science

**Practical**

- Alpha diversity: estimation, analysis, and visualization 

----------------------------------------------------------------

## Wednesday 14 July - Beta diversity

**Demo**

- Community similarity 

**Practical**

- Beta diversity: estimation, analysis, and visualization

-----------------------------------------------------------------

## Thursday 15 July - Differential abundance

**Lecture**

- Differential abundance analysis methods 


**Practical**

- Differential abundance in practice


**Lecture**

- Overview of microbiota data science methods & concepts

-----------------------------------------------------------------

## Friday 16 July: Presentations & closing

**Student presentations** on microbiome data analytics




