---
title: "Getting Started"
author: "`r authors`"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Getting started


## Checklist (before the course)

Install the following software in advance in order to avoid
unnecessary delays and leaving more time for the course contents.


* [R (version >4.1.0)](https://www.r-project.org/) 

* [RStudio](https://www.rstudio.com/products/rstudio/download/);
  choose "Rstudio Desktop" to download the latest version. Optional
  but preferred. For further details, check the [Rstudio home
  page](https://www.rstudio.com/).

* [Install and load required R packages](install.html).

* After a successful installation you can start trying out the
  case study examples in this training material


## Support and resources

For additional reading and online material, see [Material](material.html) section

For online support on installation and other matters, you can join us at:

 * Users: [miaverse Gitter channel](https://gitter.im/microbiome/miaverse?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
 * Developers: [Bioconductor Slack](https://bioc-community.herokuapp.com) #microbiomeexperiment channel




