# Importing microbiome data

This section demonstrates how to import microbiome profiling data in R.


## Data access

**Download the data** from
  [data](https://github.com/microbiome/course_2021_radboud/tree/main/data)
  subfolder.

We use example data from the following publication: Tengeler AC _et
al._ (2020) [**Gut microbiota from persons with
attention-deficit/hyperactivity disorder affects the brain in
mice**](https://doi.org/10.1186/s40168-020-00816-x). Microbiome
8:44.

In this study, mice are colonized with microbiota from participants
with ADHD (attention deficit hyperactivity disorder) and healthy
participants.  The aim of the study was to assess whether the mice
display ADHD behaviors after being inoculated with ADHD microbiota,
suggesting a role of the microbiome in ADHD pathology.


## Importing microbiome data in R

**Import example data** by modifying the examples in the online book
section on [data exploration and
manipulation](https://microbiome.github.io/OMA/data-introduction.html#loading-experimental-microbiome-data). The
data files in our example are in _biom_ format, which is a standard
file format for microbiome data. Other file formats exist as well, and
import details vary by platform.

Here, we import _biom_ data files into a specific data container (structure)
in R, _TreeSummarizedExperiment_ (TSE) [Huang et
al. (2020)](https://f1000research.com/articles/9-1246). This provides
the basis for downstream data analysis in the _miaverse_ data science
framework.

In this course, we focus on downstream analysis of taxonomic profiling
data, and assume that the data has already been appropriately
preprocessed and available in the TSE format. In addition to our
example data, further demonstration data sets are readily available in
the TSE format through
[microbiomeDataSets](https://bioconductor.org/packages/release/data/experiment/html/microbiomeDataSets.html).



