---
title: "Installation of the necessary R packages"
output: html_document
---

This notebook shows how to install all required packages. The
installation needs to be done just once.


```{r warning = FALSE, message = FALSE}
# List of packages that we need from cran and bioc 
cran_pkg <- c("BiocManager", "dplyr", "ecodist", "ggplot2", "gridExtra", "knitr", "vegan")
bioc_pkg <- c("ANCOMBC", "ape", "DESeq2",  "DirichletMultinomial", "mia", "miaViz")

# Gets those packages that are already installed
cran_pkg_already_installed <- cran_pkg[ cran_pkg %in% installed.packages() ]
bioc_pkg_already_installed <- bioc_pkg[ bioc_pkg %in% installed.packages() ]

# Gets those packages that need to be installed
cran_pkg_to_be_installed <- setdiff(cran_pkg, cran_pkg_already_installed)
bioc_pkg_to_be_installed <- setdiff(bioc_pkg, bioc_pkg_already_installed)
```

```{r warning = FALSE, message = FALSE}
# If there are packages that need to be installed, installs them
if( length(cran_pkg_to_be_installed) ) {
   install.packages(cran_pkg_to_be_installed)
}
```

```{r warning = FALSE, message = FALSE}
# If there are packages that need to be installed, installs them
if( length(bioc_pkg_to_be_installed) ) {
   BiocManager::install(bioc_pkg_to_be_installed, ask = F)
}
```

```{r warning = FALSE, message = FALSE}
# Loading all packages into session
sapply(c(cran_pkg , bioc_pkg), require, character.only = TRUE)
```

